// ============================================================================
// Core Domain Types
// ============================================================================

/**
 * Project entity from database
 */
export interface Project {
  id: string;
  title: string;
  problem: string;
  constraints: string | null;
  createdAt: Date;
  updatedAt: Date;
  userId: string | null;
}

/**
 * Simplified project type for pipeline execution
 */
export interface PipelineProject {
  id: string;
  title: string;
  problem: string;
  constraints: string | null;
}

// ============================================================================
// LangGraph Pipeline Types
// ============================================================================

/**
 * Clarifications generated by the clarifier node
 * Index signature allows compatibility with Prisma's JSON type
 */
export interface Clarifications {
  questions?: string[];
  assumptions?: string[];
  scope?: string;
  [key: string]: string | string[] | undefined;
}

/**
 * High-Level Design generated by the HLD drafter node
 * Index signature allows compatibility with Prisma's JSON type
 */
export interface HLD {
  modules?: string[];
  dataFlows?: string[];
  risks?: string[];
  nfrs?: string[];
  [key: string]: string[] | undefined;
}

/**
 * Raw ticket generated by the ticket slicer node
 */
export interface RawTicket {
  title: string;
  description: string;
  acceptanceCriteria: string;
}

/**
 * Ticket with estimates added by the estimator node
 */
export interface EstimatedTicket extends RawTicket {
  estimateHours: number;
  tshirtSize: string;
}

/**
 * Complete ticket with priority and sprint assignment
 */
export interface FinalTicket extends EstimatedTicket {
  priority: number;
  sprint: number;
  dependencies: string[];
  tags: string[];
}

/**
 * Ticket data from pipeline (may have acceptanceCriteria as array or string)
 */
export interface PipelineTicket {
  title: string;
  description: string;
  acceptanceCriteria: string[] | string;
  estimateHours: number;
  tshirtSize: string;
  priority: number;
  sprint: number;
  dependencies?: string[];
  tags?: string[];
}

// ============================================================================
// Database Entity Types
// ============================================================================

/**
 * Ticket entity from database
 */
export interface Ticket {
  id: string;
  runId: string;
  title: string;
  description: string;
  acceptanceCriteria: string;
  estimateHours: number | null;
  tshirtSize: string | null;
  priority: number;
  sprint: number | null;
  status: string;
  dependencies: string[];
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Run entity from database
 */
export interface Run {
  id: string;
  projectId: string;
  status: string;
  clarifications?: Clarifications;
  hld?: HLD;
  tokensUsed: number;
  durationMs: number | null;
  errorMessage: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Run with related project data
 */
export interface RunWithProject extends Run {
  project: Project;
}

/**
 * Run with related project and tickets
 */
export interface RunWithDetails extends Run {
  project: Project;
  tickets: Ticket[];
}

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Project with related runs
 */
export interface ProjectWithRuns extends Project {
  runs: Run[];
}

/**
 * Rate limit response
 */
export interface RateLimitResponse {
  success: boolean;
  reset: Date;
  remaining: number;
}

/**
 * Error response
 */
export interface ErrorResponse {
  error: string;
  code: string;
  statusCode: number;
  details?: ValidationDetails | ValidationDetails[] | ZodIssue[];
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * Validation error details
 */
export interface ValidationDetails {
  field?: string;
  message: string;
  code?: string;
}

/**
 * Zod validation issue
 */
export interface ZodIssue {
  code: string;
  path: (string | number)[];
  message: string;
}

/**
 * Zod error with issues array
 */
export interface ZodError {
  issues: ZodIssue[];
}
